# Project information
site_name: 'EnID Developer Zone'
site_description: 'Test für neue Doku'
site_author: 'mste'
site_url: 'https://1701.github.io/d/'

# Theme Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: '#76B82A'
    accent: '#545454'
  font: false
    # text: 'IBM Plex Sans'
    # code: 'Roboto Mono'
  logo: 'images/logo.png'
  custom_dir: custom_theme/
  
# Github Repo
# repo_name: '1701/d'
# repo_url: 'https://github.com/1701/d'

# Site Navigation
nav:
    - About : index.md
    - Developer Portal: devp_services.md
    - SSO Integration: doc_sso_developer.md
    - CMP Integration:
        - General information: cmp_1.md
        - Browser-based API: cmp_2.md
        - Server-based API: cmp_3.md
        - Data export for partners: cmp_4.md
    - Plugins: plugins.md
    - FAQ: faq.md

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  
# Custom Search Settings  
extra:
  manifest: 'manifest.webmanifest'
  search:
    language: 'en, de'
    
# PlantUML
plugins:
  - search
  - build_plantuml:
      render: "server" # or "local" for local rendering
      bin_path: "/usr/local/bin/plantuml" # ignored when render: server
      server: "http://www.plantuml.com/plantuml" # offical plantuml server
      output_format: "svg" # or "png"
      diagram_root: "docs/diagrams" # should reside under docs_dir
      output_folder: "out"
      input_folder: "src"

    # Override CSS      
extra_css:
  - 'stylesheets/extra.css'
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css

# JS 
extra_javascript:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js