# Project information
site_name: 'netID Developer Zone'
site_description: 'Developer Zone for netID, the european login standard of the European netID Foundation.'
site_author: 'mste'
site_url: 'https://1701.github.io/d/'

# Theme Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: '#76B82A'
    accent: '#545454'
  font: 
    text: 'IBM Plex Sans'
    code: 'Roboto Mono'
  logo: 'images/logo.png'
  favicon: 'images/favicon.ico'
  custom_dir: custom_theme/
  features:
    - tabs

# Github Repo
# repo_name: '1701/d'
# repo_url: 'https://github.com/1701/d'

# Site Navigation
nav:
    - About netID: index.md
    - Developer Portal:
        - Getting started: devportal/get_started.md
        - Tutorials:
            - Services: devportal/tutorial/services.md
            - Clients: devportal/tutorial/clients.md
            - User Management: devportal/tutorial/users.md
            - Test User: devportal/tutorial/testuser.md
        - KPI Reports: devportal/reporting.md
    - Single Sign-on Integration: 
        - Technical Details: sso/doc_sso_developer.md
        - Styleguide: sso/styleguide.md
        - Plugins: sso/plugins.md
    - CMP Integration:
        - General information: cmp/index.md
        - Browser-based API: cmp/browser-based.md
        - Server-based API: cmp/server-based.md
        - Data export API: cmp/export.md
    - Glossary: glossary.md
    - FAQ: faq.md

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

    
# PlantUML
plugins:
  - search
  - build_plantuml:
      render: "server" # or "local" for local rendering
      bin_path: "/usr/local/bin/plantuml" # ignored when render: server
      server: "http://www.plantuml.com/plantuml" # offical plantuml server
      output_format: "svg" # or "png"
      diagram_root: "docs/diagrams" # should reside under docs_dir
      output_folder: "out"
      input_folder: "src"

    # Override CSS      
extra_css:
  - 'stylesheets/extra.css'

