@startuml

skinparam sequence {
	ArrowColor #76b82a
	ActorBorderColor #76b82a
    ActorBackgroundColor #FFF
	ActorFontColor #000
    ActorFontName Arial
	ActorFontSize 17

	LifeLineBorderColor #76b82a
	LifeLineBackgroundColor #76b82a
	
	ParticipantBorderColor #76b82a
	ParticipantBackgroundColor #76b82a
	ParticipantFontName Arial
	ParticipantFontSize 17
	ParticipantFontColor #FFF

}

autonumber "<b>[00]"
participant  "CMP JS" as cmp
participant  "Browser" as br
participant  "Permission Layer" as pl
participant  "Read Service" as rs
participant  "IdentWrite Service" as ws

cmp -> br : Check local/cached status at netID Partner
activate br
br -> cmp : response: unknown user, no privacy status present
deactivate br
group Check Status (privacy settings, user authentication)
    cmp -> rs : try to retrieve privacy status for authenticated user
    activate rs
    rs -> cmp : response - OK, CONSENT_REQUIRED, no privacy status present
    deactivate rs
    end
group Display CMP User Interface - establish privacy status 
    cmp -> br : Display CMP UI - establish privacy status
    activate br
    br -> cmp : response: User choices for privacy status
    deactivate br
    end
Group Permantenly store privacy status with user account
cmp -> ws : store no privacy status via the WRITE SERVICE
activate ws
ws -> cmp : response: OK, TPID, privacy status 
deactivate ws
end
cmp -> br : cache local status in netID Partner domain
activate br
br -> cmp : response
deactivate br
@enduml